
DROP DATABASE IF EXISTS wishList;
CREATE DATABASE wishList;
USE wishList; 

CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT,
    FULLNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    USER_PASSWORD VARCHAR(255),
    PRIMARY KEY(USER_ID)
);

CREATE TABLE WISHLIST (
    WISHLIST_ID INT AUTO_INCREMENT,
    WISHLIST_NAME VARCHAR(255),
    USER_ID INT,
    PRIMARY KEY(WISHLIST_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE WISH (
    WISH_ID INT AUTO_INCREMENT,
    WISH_NAME VARCHAR(255),
    LINK_TO_WISH VARCHAR(2000),
    WISH_DESCRIPTION VARCHAR(6000),
    WISH_PRICE DECIMAL,
    WISHLIST_ID INT,
    PRIMARY KEY(WISH_ID),
    FOREIGN KEY(WISHLIST_ID) REFERENCES WISHLIST(WISHLIST_ID)
);
